export const messagesData = {
    1: [
      { sender: 'lhoj', message: 'How are you?', time: '10:00 AM' },
      { sender: 'You', message: 'I am fine.', time: '10:01 AM' },
      { sender: 'lhoj', message: 'What are you doing?', time: '10:02 AM' },
      { sender: 'You', message: 'Just working on a project.', time: '10:03 AM' },
      { sender: 'lhoj', message: 'That sounds interesting.', time: '10:04 AM' },
      { sender: 'You', message: 'Yeah, it is!', time: '10:05 AM' },
      { sender: 'lhoj', message: 'Good luck with that.', time: '10:06 AM' },
      { sender: 'You', message: 'Thank you!', time: '10:07 AM' },
      { sender: 'lhoj', message: 'No problem.', time: '10:08 AM' },
      { sender: 'You', message: 'Talk to you later.', time: '10:09 AM' },
    ],
    2: [
      { sender: 'kbh', message: 'Can you send me the assignment?', time: '10:02 AM' },
      { sender: 'You', message: 'Sure, give me a minute.', time: '10:03 AM' },
      { sender: 'kbh', message: 'Thanks!', time: '10:04 AM' },
      { sender: 'You', message: 'No problem.', time: '10:05 AM' },
      { sender: 'kbh', message: 'I appreciate it.', time: '10:06 AM' },
      { sender: 'You', message: 'Anytime.', time: '10:07 AM' },
      { sender: 'kbh', message: 'Got it, thanks again.', time: '10:08 AM' },
      { sender: 'You', message: 'You\'re welcome.', time: '10:09 AM' },
      { sender: 'kbh', message: 'See you later.', time: '10:10 AM' },
      { sender: 'You', message: 'Bye.', time: '10:11 AM' },
    ],
    3: [
      { sender: 'kih', message: 'Please provide your application number.', time: '10:00 AM' },
      { sender: 'You', message: 'Here it is: 123456.', time: '10:01 AM' },
      { sender: 'kih', message: 'Thank you.', time: '10:02 AM' },
      { sender: 'You', message: 'You\'re welcome.', time: '10:03 AM' },
      { sender: 'kih', message: 'Your application is under review.', time: '10:04 AM' },
      { sender: 'You', message: 'Great, thanks!', time: '10:05 AM' },
      { sender: 'kih', message: 'We will update you soon.', time: '10:06 AM' },
      { sender: 'You', message: 'I appreciate it.', time: '10:07 AM' },
      { sender: 'kih', message: 'Have a nice day.', time: '10:08 AM' },
      { sender: 'You', message: 'You too.', time: '10:09 AM' },
    ],
    4: [
      { sender: 'khjoh', message: 'Did you check the link I sent?', time: '10:00 AM' },
      { sender: 'You', message: 'Not yet, I will check now.', time: '10:01 AM' },
      { sender: 'khjoh', message: 'Okay, let me know if it works.', time: '10:02 AM' },
      { sender: 'You', message: 'Sure, give me a moment.', time: '10:03 AM' },
      { sender: 'khjoh', message: 'Take your time.', time: '10:04 AM' },
      { sender: 'You', message: 'The link is working, thanks!', time: '10:05 AM' },
      { sender: 'khjoh', message: 'Great!', time: '10:06 AM' },
      { sender: 'You', message: 'Really appreciate it.', time: '10:07 AM' },
      { sender: 'khjoh', message: 'Anytime.', time: '10:08 AM' },
      { sender: 'You', message: 'Talk to you later.', time: '10:09 AM' },
    ],
    5: [
      { sender: 'kihiu', message: 'Are you coming to the reunion?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, I am planning to.', time: '10:01 AM' },
      { sender: 'kihiu', message: 'That\'s great!', time: '10:02 AM' },
      { sender: 'You', message: 'Looking forward to it.', time: '10:03 AM' },
      { sender: 'kihiu', message: 'Me too!', time: '10:04 AM' },
      { sender: 'You', message: 'See you there.', time: '10:05 AM' },
      { sender: 'kihiu', message: 'Definitely!', time: '10:06 AM' },
      { sender: 'You', message: 'Take care.', time: '10:07 AM' },
      { sender: 'kihiu', message: 'You too.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    6: [
      { sender: 'lkjpk', message: 'Can we schedule a meeting?', time: '10:00 AM' },
      { sender: 'You', message: 'Sure, when are you available?', time: '10:01 AM' },
      { sender: 'lkjpk', message: 'How about tomorrow?', time: '10:02 AM' },
      { sender: 'You', message: 'Tomorrow works for me.', time: '10:03 AM' },
      { sender: 'lkjpk', message: 'Great, let\'s do it in the afternoon.', time: '10:04 AM' },
      { sender: 'You', message: 'Perfect, see you then.', time: '10:05 AM' },
      { sender: 'lkjpk', message: 'Looking forward to it.', time: '10:06 AM' },
      { sender: 'You', message: 'Me too.', time: '10:07 AM' },
      { sender: 'lkjpk', message: 'Take care.', time: '10:08 AM' },
      { sender: 'You', message: 'You too.', time: '10:09 AM' },
    ],
    7: [
      { sender: 'oihuou', message: 'Did you finish the project?', time: '10:00 AM' },
      { sender: 'You', message: 'Almost, just a few tweaks left.', time: '10:01 AM' },
      { sender: 'oihuou', message: 'That\'s good to hear.', time: '10:02 AM' },
      { sender: 'You', message: 'Yeah, it\'s coming along well.', time: '10:03 AM' },
      { sender: 'oihuou', message: 'Keep up the good work!', time: '10:04 AM' },
      { sender: 'You', message: 'Thanks for the support.', time: '10:05 AM' },
      { sender: 'oihuou', message: 'No problem.', time: '10:06 AM' },
      { sender: 'You', message: 'I\'ll show it to you once it\'s done.', time: '10:07 AM' },
      { sender: 'oihuou', message: 'I\'d love that.', time: '10:08 AM' },
      { sender: 'You', message: 'Great, see you later.', time: '10:09 AM' },
    ],
    8: [
      { sender: 'Sjuad', message: 'Are we meeting today?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, at 5 PM.', time: '10:01 AM' },
      { sender: 'Sjuad', message: 'Same place?', time: '10:02 AM' },
      { sender: 'You', message: 'Yes, see you there.', time: '10:03 AM' },
      { sender: 'Sjuad', message: 'Alright.', time: '10:04 AM' },
      { sender: 'You', message: 'Looking forward to it.', time: '10:05 AM' },
      { sender: 'Sjuad', message: 'Me too.', time: '10:06 AM' },
      { sender: 'You', message: 'Let\'s have fun.', time: '10:07 AM' },
      { sender: 'Sjuad', message: 'Definitely.', time: '10:08 AM' },
      { sender: 'You', message: 'See you soon.', time: '10:09 AM' },
    ],
    9: [
      { sender: 'Ahjooj', message: 'Did you get the documents?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, I did.', time: '10:01 AM' },
      { sender: 'Ahjooj', message: 'Perfect.', time: '10:02 AM' },
      { sender: 'You', message: 'Thanks for sending them.', time: '10:03 AM' },
      { sender: 'Ahjooj', message: 'No problem.', time: '10:04 AM' },
      { sender: 'You', message: 'I\'ll review them now.', time: '10:05 AM' },
      { sender: 'Ahjooj', message: 'Let me know if you need anything.', time: '10:06 AM' },
      { sender: 'You', message: 'Will do.', time: '10:07 AM' },
      { sender: 'Ahjooj', message: 'Thanks.', time: '10:08 AM' },
      { sender: 'You', message: 'You\'re welcome.', time: '10:09 AM' },
    ],
    10: [
      { sender: 'yuuo', message: 'Can you send me the report?', time: '10:00 AM' },
      { sender: 'You', message: 'I will send it now.', time: '10:01 AM' },
      { sender: 'yuuo', message: 'Thanks!', time: '10:02 AM' },
      { sender: 'You', message: 'No problem.', time: '10:03 AM' },
      { sender: 'yuuo', message: 'I appreciate it.', time: '10:04 AM' },
      { sender: 'You', message: 'Anytime.', time: '10:05 AM' },
      { sender: 'yuuo', message: 'Got it, thanks again.', time: '10:06 AM' },
      { sender: 'You', message: 'You\'re welcome.', time: '10:07 AM' },
      { sender: 'yuuo', message: 'See you later.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    11: [
      { sender: 'hijuo', message: 'Here is the latest update.', time: '10:00 AM' },
      { sender: 'You', message: 'Thanks for the info.', time: '10:01 AM' },
      { sender: 'hijuo', message: 'You\'re welcome.', time: '10:02 AM' },
      { sender: 'You', message: 'Is there anything else?', time: '10:03 AM' },
      { sender: 'hijuo', message: 'No, that\'s all for now.', time: '10:04 AM' },
      { sender: 'You', message: 'Okay, thanks again.', time: '10:05 AM' },
      { sender: 'hijuo', message: 'Anytime.', time: '10:06 AM' },
      { sender: 'You', message: 'Talk to you later.', time: '10:07 AM' },
      { sender: 'hijuo', message: 'See you.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    12: [
      { sender: 'higuu', message: 'Are you joining the game tonight?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, I am.', time: '10:01 AM' },
      { sender: 'higuu', message: 'Awesome!', time: '10:02 AM' },
      { sender: 'You', message: 'Looking forward to it.', time: '10:03 AM' },
      { sender: 'higuu', message: 'Me too.', time: '10:04 AM' },
      { sender: 'You', message: 'Let\'s win this.', time: '10:05 AM' },
      { sender: 'higuu', message: 'Definitely.', time: '10:06 AM' },
      { sender: 'You', message: 'See you there.', time: '10:07 AM' },
      { sender: 'higuu', message: 'See you.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    13: [
      { sender: 'ftrds', message: 'Did you get my email?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, I got it.', time: '10:01 AM' },
      { sender: 'ftrds', message: 'Great, thanks.', time: '10:02 AM' },
      { sender: 'You', message: 'No problem.', time: '10:03 AM' },
      { sender: 'ftrds', message: 'I\'ll follow up soon.', time: '10:04 AM' },
      { sender: 'You', message: 'Okay, sounds good.', time: '10:05 AM' },
      { sender: 'ftrds', message: 'Talk to you later.', time: '10:06 AM' },
      { sender: 'You', message: 'See you.', time: '10:07 AM' },
      { sender: 'ftrds', message: 'Bye.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    14: [
      { sender: 'rtofr', message: 'Can you review this document?', time: '10:00 AM' },
      { sender: 'You', message: 'Sure, I\'ll take a look now.', time: '10:01 AM' },
      { sender: 'rtofr', message: 'Thank you.', time: '10:02 AM' },
      { sender: 'You', message: 'You\'re welcome.', time: '10:03 AM' },
      { sender: 'rtofr', message: 'How does it look?', time: '10:04 AM' },
      { sender: 'You', message: 'It looks good.', time: '10:05 AM' },
      { sender: 'rtofr', message: 'That\'s great to hear.', time: '10:06 AM' },
      { sender: 'You', message: 'Just a few minor changes needed.', time: '10:07 AM' },
      { sender: 'rtofr', message: 'I\'ll fix them.', time: '10:08 AM' },
      { sender: 'You', message: 'Okay, thanks.', time: '10:09 AM' },
    ],
    15: [
      { sender: 'funda', message: 'Can we meet tomorrow?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, what time?', time: '10:01 AM' },
      { sender: 'funda', message: 'How about 2 PM?', time: '10:02 AM' },
      { sender: 'You', message: 'Works for me.', time: '10:03 AM' },
      { sender: 'funda', message: 'Great, see you then.', time: '10:04 AM' },
      { sender: 'You', message: 'Looking forward to it.', time: '10:05 AM' },
      { sender: 'funda', message: 'Me too.', time: '10:06 AM' },
      { sender: 'You', message: 'Take care.', time: '10:07 AM' },
      { sender: 'funda', message: 'You too.', time: '10:08 AM' },
      { sender: 'You', message: 'Bye.', time: '10:09 AM' },
    ],
    16: [
      { sender: 'gundf', message: 'Did you complete the assignment?', time: '10:00 AM' },
      { sender: 'You', message: 'Yes, I did.', time: '10:01 AM' },
      { sender: 'gundf', message: 'Great, can you send it to me?', time: '10:02 AM' },
      { sender: 'You', message: 'Sure, I will send it now.', time: '10:03 AM' },
    ]
};


  